name: test
augment: []
db_path: data/processed
out_path: models/checkpoints
max_steps: 100 # 6000000
val_every: 10 # 10000
save_every: 5000 # 500000
n_signal: ${N_SIGNAL}
channels: ${N_CHANNELS}
batch: 8
workers: 8
gpu: -1
derivative: 2
normalize: False
rand_pitch: null
ema: null
smoke_test: True
ckpt: null
progress: True
