stages:
  preprocess:
    cmd: python3 scripts/preprocess.py hydra/job_logging=disabled hydra/hydra_logging=disabled
    deps:
      - scripts/preprocess.py
      - data/raw/
    outs:
      - data/processed/
  train:
    cmd: python3 scripts/train.py hydra/job_logging=disabled hydra/hydra_logging=disabled
    deps:
      - scripts/train.py
      - rave/
      - data/processed/
    outs:
      - models/checkpoints/
  export:
    cmd: python scripts/export.py hydra/job_logging=disabled hydra/hydra_logging=disabled
    deps:
      - scripts/export.py
      - models/checkpoints/
    outs:
      - models/exports/
