preprocess:
  input_path: data/raw
  output_path: data/processed
  num_signal: 131072
  sampling_rate: 44100
model:
train:
  name: test
  db_path: data/processed
  out_path: models/checkpoints
  max_steps: 100 # 6000000
  val_every: 10 # 10000
  save_every: 5000 # 500000
  channels: 1
  batch: 8
  workers: 8
  gpu: -1
  derivative: 2
  normalize: False
  smoke_test: False
export:
  run: models/checkpoints/test
  streaming: True
  fidelity: 0.999
  name: test
  output: models/exports
